# Generated by Django 2.1.1 on 2019-01-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='menu',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Menu', verbose_name='Название меню'),
            preserve_default=False,
        ),
    ]
